name: check

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
permissions: read-all

jobs:
  markdown:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo gem install mdl
          mdl -s docs/linter/readme_style.rb README.md
          mdl -s docs/linter/base_style.rb CONTRIBUTING.md docs .github

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: software-mansion/setup-scarb@v1
      - uses: foundry-rs/setup-snfoundry@v2
        with:
          starknet-foundry-version: 0.12.0
      - name: Run cairo tests
        run: snforge test unit_tests
